### PR TITLE
allow ranges

### PR DESCRIPTION
**Pull request by davidbirdsong**
informed guesswork to stop requiring this file to be bumped for
every release of listed deps

### CODE REVIEW

**Comment by cablehead** [comment]
Oh wow. This is being used?

**Comment by davidbirdsong** [comment]
you knew it was only a matter of time

**Comment by cablehead** [comment]
It might need a quick touch up. It might not too.. it's been so long since I've taken this lib for a spin.

**Comment by cablehead** [comment]
Went with a slightly more liberal requirements range...

**Pull request closed without merging**
